import { SITE } from '../config/site'

/*
  Canonical URLs follow the generated sitemap: production origin, no query
  string, trailing slash for every published route. Search and filters are UI
  state, not alternate canonical documents.
*/
export function canonicalUrl(pathname: string): string {
  if (!pathname || pathname === '/') return `${SITE.canonicalDomain}/`
  const clean = `/${pathname.split('/').filter(Boolean).join('/')}`
  return `${SITE.canonicalDomain}${clean}/`
}

/* ── Per-route share art ───────────────────────────────────────────────────
  Distinct OG cards live at /og/<section>.png (1200x630, PNG — scrapers reject
  webp). A section with no dedicated card falls back to the site default. The
  cards are generated by scripts/og-cards.mjs from assets the atlas already owns
  (the Anton wordmark, the warm field, grip stills); they carry no fabricated
  number. Keep this map in lockstep with what actually exists in public/og.
*/
export type OgSection =
  | 'home'
  | 'repertoire'
  | 'craftsmen'
  | 'lost-pitches'
  | 'grips'
  | 'learn'

const OG_DEFAULT = `${SITE.canonicalDomain}/og-image.png`

const OG_CARD: Record<OgSection, string> = {
  home: `${SITE.canonicalDomain}/og/home.png`,
  repertoire: `${SITE.canonicalDomain}/og/repertoire.png`,
  craftsmen: `${SITE.canonicalDomain}/og/craftsmen.png`,
  'lost-pitches': `${SITE.canonicalDomain}/og/lost-pitches.png`,
  grips: `${SITE.canonicalDomain}/og/grips.png`,
  learn: `${SITE.canonicalDomain}/og/learn.png`,
}

/** The 1200x630 OG/Twitter image fields for a section, ready to spread into
    useSeoMeta. Pass no section (or a missing card) to get the site default.
    Uses unhead's object form so og:image:width/height/alt/type all emit. */
export function ogImageMeta(section?: OgSection, alt?: string) {
  const url = section ? OG_CARD[section] : OG_DEFAULT
  const imageAlt = alt ?? `${SITE.siteName} — ${SITE.positioning}`
  const image = { url, width: 1200, height: 630, alt: imageAlt, type: 'image/png' } as const
  return {
    ogImage: image,
    twitterImage: image,
    twitterCard: 'summary_large_image',
  } as const
}

/* ── Structured data (schema.org JSON-LD) ─────────────────────────────────── */

type JsonLdNode = Record<string, unknown>

/** The site-level graph: WebSite + Organization. Stable across the whole site
    (the home page also carries its CreativeWork via siteJsonLd). */
export function organizationJsonLd(): JsonLdNode {
  return {
    '@type': 'Organization',
    '@id': `${SITE.canonicalDomain}/#org`,
    name: SITE.siteName,
    url: `${SITE.canonicalDomain}/`,
    slogan: SITE.tagline,
    description: SITE.positioning,
  }
}

/** The site-level graph. WebSite + Organization are stable identity and belong
    on every route; the home field-manual CreativeWork only describes '/', so it
    is included on the home page alone (pass `home: false` on inner routes to
    drop it and avoid repeating a home-scoped node site-wide). */
export function siteJsonLd(home: boolean = true) {
  const graph: Record<string, unknown>[] = [
    {
      '@type': 'WebSite',
      '@id': `${SITE.canonicalDomain}/#website`,
      name: SITE.siteName,
      url: `${SITE.canonicalDomain}/`,
      description:
        'A grip-first field manual for pitching grips, variants, craftsmen, and sourced community notes.',
      inLanguage: 'en',
      publisher: { '@id': `${SITE.canonicalDomain}/#org` },
      potentialAction: {
        '@type': 'SearchAction',
        target: `${SITE.canonicalDomain}/repertoire/?q={search_term_string}`,
        'query-input': 'required name=search_term_string',
      },
    },
    organizationJsonLd(),
  ]
  if (home) {
    graph.push({
      '@type': 'CreativeWork',
      '@id': `${SITE.canonicalDomain}/#field-manual`,
      name: `${SITE.siteName}: The Living Field Manual for Pitching Grips`,
      url: `${SITE.canonicalDomain}/`,
      headline: 'How pitchers grip and shape the baseball, labeled by source.',
      abstract:
        'Grip-first reference for pitch specimens, variants, craftsmen, lost pitches, and community field notes. Sourced, not corrected.',
      isAccessibleForFree: true,
      inLanguage: 'en',
      creator: { '@id': `${SITE.canonicalDomain}/#org` },
      isPartOf: { '@id': `${SITE.canonicalDomain}/#website` },
    })
  }
  return { '@context': 'https://schema.org', '@graph': graph }
}

/** One step in a breadcrumb trail. `to` is a site-relative path; the last item
    (the current page) may omit it. Mirrors the visual <Breadcrumb> trail. */
export interface CrumbStep {
  name: string
  /** Site-relative path, e.g. '/repertoire'. Omit on the current (last) page. */
  to?: string
}

/** A BreadcrumbList for a nested route. Every item gets an absolute item URL so
    the chain is unambiguous; the current page resolves to `pageUrl`. */
export function breadcrumbJsonLd(trail: CrumbStep[], pageUrl: string): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((step, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: step.name,
      item: step.to ? canonicalUrl(step.to) : pageUrl,
    })),
  }
}

export interface ContentJsonLdInput {
  /** Schema.org type for the page's primary entity. */
  type: 'CreativeWork' | 'Article'
  url: string
  name: string
  description: string
  /** Breadcrumb trail to render alongside, when the route is nested. */
  breadcrumb?: CrumbStep[]
}

/** The per-page content graph: a CreativeWork (or Article) for a content page,
    optionally bundled with its BreadcrumbList. Every field is real page copy —
    no fabricated stat ever enters the JSON-LD (the doctrine applies to metadata
    too). Returns an @graph so one <script> carries both nodes. */
export function contentJsonLd(input: ContentJsonLdInput) {
  const work: JsonLdNode = {
    '@type': input.type,
    '@id': `${input.url}#content`,
    name: input.name,
    headline: input.name,
    url: input.url,
    description: input.description,
    isAccessibleForFree: true,
    inLanguage: 'en',
    isPartOf: { '@id': `${SITE.canonicalDomain}/#website` },
    publisher: { '@id': `${SITE.canonicalDomain}/#org` },
  }
  const graph: JsonLdNode[] = [work]
  if (input.breadcrumb && input.breadcrumb.length > 0) {
    const crumbs = breadcrumbJsonLd(input.breadcrumb, input.url)
    graph.push({ '@type': 'BreadcrumbList', itemListElement: crumbs.itemListElement })
  }
  return { '@context': 'https://schema.org', '@graph': graph }
}
