project_id = "cloeoulvrrfcbitrjpso"

[functions.delete-account]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-account/index.ts"

[functions.summarize-thread]
enabled = true
verify_jwt = true
entrypoint = "./functions/summarize-thread/index.ts"
