# Usage notes for every token, written from the site's stylesheet (src/index.css at
# main@4098cbd) and measured in a browser: the value at the top level, and what
# changes inside `.field-cream`, the one cream scope.
CREAM = 'inside `.field-cream` it is'

COLOR = {
    'color-black': 'Pure black. Tailwind base color; the brand reaches for `color-void` instead.',
    'color-white': 'Pure white. Tailwind base color; text on a red CTA uses `color-cta-text`.',
    'color-paper': f'The heritage page paper. The site remaps it to the void (#070509) at the top level so legacy `bg-paper` surfaces read dark; {CREAM} the cream ground #f4eee0.',
    'color-paper-2': f'Deeper heritage paper for alternating sections. Void-panel #0e0b15 at the top level; {CREAM} #eae2d2.',
    'color-stage': 'The warm stage behind hero and colophon (`.on-stage`); the same near-black as the void.',
    'color-press': 'Raised warm charcoal: cards on the table. The ground of `surface-card` and the `Card` component; `color-bone` reads 14.7:1 on it.',
    'color-ink': f'Primary heritage ink. Bone (#f6f1e6) at the top level so legacy `text-ink` reads on the void; {CREAM} #14161b, which reads 15.6:1 on `surface-cream`.',
    'color-ink-2': f'Secondary heritage ink. #c2c7d6 on the void; {CREAM} slate #3f4654 (8.2:1 on cream).',
    'color-ink-3': f'Tertiary ink and hairline tone. #7c8294 on the void (5.3:1); {CREAM} #5c6473 (5.2:1 on cream).',
    'color-seam': f'The seam red. At the top level the bright stitch #ff2d44 (5.5:1 on the void); {CREAM} the deeper #c8102e, which is `cta-bg` there and reads 5.1:1 on cream. Never small text on the void at the cream value (3.4:1).',
    'color-seam-deep': f'Pressed seam red for the CTA hover (`cta-bg-hover`). Resolved from `color-mix(in srgb, #ff2d44 78%, #2a0a10)` at the top level; {CREAM} the mix of #c8102e.',
    'color-powder': f'Columbia powder blue: secondary accent and data tints. #7fc6ff on the void; {CREAM} #6cace4.',
    'color-navy': f'Heritage navy for prestige and structure. Remapped to warm light #d8d1c0 on the void; {CREAM} #0c2340.',
    'color-navy-2': f'Lifted navy for hover borders and plate edges. #efe9da on the void; {CREAM} #15406e.',
    'color-navy-line': f'Faint navy line for plate borders. 16% warm light on the void; {CREAM} navy at 22%.',
    'color-cta-text': 'Text on the red CTA field (`cta-text`). White on `color-seam` #c8102e reads 5.9:1.',
    'color-leather': 'Saddle leather: the kicker ink on the cream field (6.4:1 on cream) and the brand-mark diamond edge.',
    'color-ok': f'Official-data green. #34e27e on the void (same as `color-ok-bright`); {CREAM} #2e7d55.',
    'color-amber': f'Reputable-analysis amber. #ffc23c on the void; {CREAM} #b07a1e.',
    'color-sand': f'Secondhand and approximate sand. #cdba8e on the void; {CREAM} #8a7a5e.',
    'color-machined': f'The machined hairline tone the `.hairline` fade is drawn in. Warm light at 20% on the void; {CREAM} slate at 38%.',
    'color-dim': 'Legacy dim text, an alias of `color-ink-2`. Declared in source but unused by any shipped rule.',
    'color-void': 'The cool near-black field: every page sits on it (`surface-page`). No page sets its own light background.',
    'color-bone': 'Primary text on the void and on `surface-card` (18:1 and 14.7:1).',
    'color-bone-2': 'Secondary text and captions on the void (11.4:1) and on cards (9.3:1).',
    'color-ok-bright': 'Official-data dot, tuned for the dark field (`confidence-official`). Status, never decoration; always beside its tier label.',
    'color-amber-bright': 'Reputable-analysis dot on the dark field (`confidence-reputable`).',
    'color-sand-bright': 'Secondhand and approximate dot on the dark field (`confidence-secondhand`).',
    'color-cyan': 'The interaction voice on the void: links, focus (`ring`), active chips and segments (`ctl-accent`), source dots, the kicker glow in a scene. 12.9:1 on the void.',
    'color-cyan-deep': 'Deeper cyan. No stylesheet rule reads it.',
    'color-seam-bright': 'The void-tuned seam red: the leather stitch, the force vector, the foil button\'s wax-seal rim, the lost and banned tier. A graphic red; 5.5:1 on the void.',
    'color-violet': 'Steel-blue palette color. No stylesheet rule reads it; pitch families take their own accents (see the brand book).',
    'color-teal-glow': 'Teal text accent (`text-teal-glow`); the same teal is a band in the foil.',
    'bevel-hi': 'Inset top highlight on the stage portrait frame (`.pa-stage-portrait`).',
    'bevel-lo': 'Paired bevel shade. No stylesheet rule reads it.',
    'color-columbia': 'Columbia blue, a heritage accent. No stylesheet rule reads it.',
    'cb-paper': 'Card-back stock. Declared on `.rfx-cardback`, the cream reverse of a specimen card.',
    'cb-paper-2': 'Deeper card-back stock, on `.rfx-cardback`.',
    'cb-ink': 'Primary ink on the card back (`.rfx-cardback`).',
    'cb-ink-2': 'Secondary ink on the card back.',
    'cb-ink-3': 'Muted ink on the card back.',
    'cb-line': 'Rules on the card back.',
    'cb-navy': 'Navy accent on the card back.',
    'cb-forest': 'Forest accent on the card back.',
    'cb-burgundy': 'Burgundy accent on the card back.',
    'cb-gold-ink': 'Gold-ink accent on the card back.',
    'plate-edge': 'Edge of a specimen plate. Declared on `.rfx-plate`, where it follows the pitch family accent (`--gc`).',
    'spec-accent': 'Specimen accent inside a specimen scope; follows `color-cyan`.',
    'color-paper-3': f'Heritage cream sand edge. #16121f on the void; {CREAM} #d8cfb8.',
    'color-cream': f'Semantic alias of the cream surface. The void at the top level; {CREAM} #f4eee0.',
    'color-panel': f'Heritage panel. #0e0b15 on the void; {CREAM} #eae2d2.',
    'kicker': f'Section eyebrow ink (`Kicker`, `.rfx-skick`). Cyan on the void; {CREAM} leather #7a4a2e.',
    'ctl-bg': f'Form control ground (`.rfx-input`, `.rfx-select`). #0b0805 on the void; {CREAM} #fffdf6.',
    'ctl-text': f'Form control text. Bone on the void; {CREAM} ink #14161b.',
    'ctl-placeholder': f'Placeholder text in controls. #7c8294 reads 5.3:1 on the void but 4.3:1 on `surface-card`; {CREAM} #5c6473.',
    'ctl-border': f'Control border: cyan at 40%, resolved from `color-mix(in srgb, var(--color-cyan) 40%, transparent)`; {CREAM} leather at 45%.',
    'ctl-accent': f'Active chip and segment fill (`Tag active`, `SegmentedToggle`). Cyan on the void; {CREAM} seam red #c8102e.',
    'ctl-on-accent': f'Text on an active chip or segment. #06121b on cyan reads 12:1; {CREAM} white on red.',
    'background': f'shadcn page ground for the generic primitives. The void; {CREAM} #f4eee0.',
    'foreground': f'shadcn text on `background`. Bone; {CREAM} ink.',
    'card': f'shadcn card ground. #0e0b15; {CREAM} #eae2d2.',
    'card-foreground': 'shadcn text on `card`.',
    'popover': f'Ground of open popovers: the Select list and menus. #0e0b15; {CREAM} #fffdf6.',
    'popover-foreground': 'Text on `popover`.',
    'primary': f'The primary-action voice: electric burnt orange, the fill of every generic primary action (the report dialog\'s submit, for one). Cyan stays the interaction voice. {CREAM} #a83607 for contrast on cream.',
    'primary-foreground': f'Ink on a `primary` fill: #1a0a04 on burnt orange reads 6.7:1; {CREAM} white.',
    'secondary': f'shadcn secondary ground. #16121f; {CREAM} #eae2d2.',
    'secondary-foreground': 'Text on `secondary`.',
    'muted': f'shadcn muted ground. #16121f; {CREAM} #eae2d2.',
    'muted-foreground': f'Muted text on the void (12:1). {CREAM} #3f4654.',
    'accent': f'shadcn hover ground for list items. #0e0b15; {CREAM} #eae2d2.',
    'accent-foreground': 'Text on `accent`.',
    'destructive': f'Destructive actions, the seam red. #ff2d44; {CREAM} #c8102e.',
    'border': f'shadcn border: bone at 12%; {CREAM} ink at 14%.',
    'input': f'shadcn input border: bone at 14%; {CREAM} ink at 18%.',
    'ring': f'Focus ring of the generic primitives: cyan. The site also draws a 2px `color-seam` outline on every focus-visible control. {CREAM} #1f6e78.',
    'chart-1': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-2': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-3': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-4': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-5': 'shadcn chart default. Declared but read by nothing the site ships.',
    'sidebar': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-primary': 'shadcn sidebar default, still the old cyan. Declared but read by nothing the site ships.',
    'sidebar-primary-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-accent': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-accent-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-border': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-ring': 'shadcn sidebar default, still the old cyan. Declared but read by nothing the site ships.',
    'color-press-2': 'Deeper press: foil-panel interiors (`.rfx-panel-foil`) and `surface-card-2`.',
    'color-bone-3': 'Tertiary text and hairline ink on the void (6.4:1) and on cards (5.2:1).',
    'surface-page': 'The page ground: the void. Set every page on it.',
    'surface-stage': 'The stage ground for heroes and the colophon.',
    'surface-card': f'Raised card ground: warm charcoal. {CREAM} #eae2d2.',
    'surface-card-2': 'The deeper card ground for foil-panel interiors.',
    'surface-cream': 'The cream ground, only inside a `.field-cream` block: card backs, cited inserts, print.',
    'surface-cream-2': 'The deeper cream ground for alternating cream sections.',
    'text-fg': f'Semantic primary text. Bone on the void; {CREAM} ink.',
    'text-fg-2': f'Semantic secondary text. `color-bone-2` on the void; {CREAM} #3f4654.',
    'text-fg-muted': f'Semantic muted text. `color-bone-3` on the void; {CREAM} #5c6473.',
    'cta-bg': 'Red CTA field (the foil button\'s wax seal), following `color-seam`.',
    'cta-bg-hover': 'Pressed red CTA field, following `color-seam-deep`.',
    'cta-text': 'Text on the red CTA field.',
    'focus-ring': 'The site\'s focus outline color: 2px `color-seam`, offset 3px, on every focus-visible control.',
    'confidence-official': f'Official-data dot. {CREAM} #2e7d55.',
    'confidence-reputable': f'Reputable-analysis dot. {CREAM} #b07a1e.',
    'confidence-secondhand': f'Secondhand, attributed dot. {CREAM} #8a7a5e.',
    'confidence-unverified': 'Unverified dot: the honest gray that makes a gap visible.',
    'border-card': f'Card edge: bone at 10% on the void; {CREAM} navy at 14%.',
    'hairline-void': 'Hairline on the void: bone at 12%. `Hairline stage` draws it.',
    'hairline-cream': 'Hairline on cream: navy at 18%. The default `Hairline` belongs on a cream field.',
}

OTHER_FAMILIES = {
    'tweet-body-margin': 'Internal to the embedded-tweet widget (`.react-tweet-theme`); not a brand spacing step.',
    'tweet-actions-icon-size': 'Internal to the embedded-tweet widget; not a brand spacing step.',
    'scroll-fade-t': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-b': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-s': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-e': 'Internal to the scroll-fade edge mask utility; set per element.',
    'spacing': 'The 4px step every padding, gap and margin multiplies (Tailwind `p-4` = 4 × this).',
    'container-xs': 'Narrow column width (20rem).',
    'container-sm': 'Small column width (24rem).',
    'container-lg': 'Card and form column width (32rem).',
    'container-2xl': 'Reading column width (42rem).',
    'container-3xl': 'Wide reading column (48rem).',
    'container-4xl': 'Section content width (56rem).',
    'container-5xl': 'Wide section width (64rem).',
    'container-6xl': 'Page content width (72rem).',
    'blur-xs': 'Smallest backdrop and glow blur.',
    'blur-sm': 'Small blur for soft glows.',
    'blur-md': 'Medium blur for overlays.',
    'blur-2xl': 'Large blur. No shipped rule reads it any more.',
    'rfxu': 'The refractor card unit: 1% of the card\'s own width (`1cqw` on `.rfx-card`), so a card\'s type and chrome scale with the card. 3.6px is its value at the 360px default.',
    'mx': 'Pointer x on a refractor card (drives the foil rake); set per card, 50% at rest.',
    'my': 'Pointer y on a refractor card; set per card, 32% at rest.',
    'radius-sm': 'Small corner: chips\' inner parts, inputs, the focus outline. Resolves from `--radius` × 0.6.',
    'radius-md': 'Medium corner for buttons and panels. `--radius` × 0.8.',
    'radius-lg': 'Large corner for cards and dialogs; equal to `--radius`.',
    'radius': 'The base corner every other radius derives from.',
    'radius-pill': 'Full pill, for filter chips and status pills only.',
    'ease-in': 'Tailwind ease-in. No shipped rule reads it; use `pa-ease-settle`.',
    'ease-out': 'Tailwind ease-out, for generic transitions in the primitives.',
    'ease-in-out': 'Tailwind ease-in-out, the default transition curve in the primitives.',
    'default-transition-duration': 'Tailwind\'s default transition length (150ms) for the generic primitives.',
    'default-transition-timing-function': 'Tailwind\'s default transition curve for the generic primitives.',
    'pa-ease-settle': 'The one house easing: a quick start that settles into stillness. Use it for every brand motion; a few older transitions (the card tilt, the specimen view transition) still carry their own curves.',
    'pa-motion-tiny': 'Press, focus and hover.',
    'pa-motion-short': 'A state change or chip settle.',
    'pa-motion-medium': 'A positional move.',
    'pa-motion-slow': 'A one-shot scroll reveal.',
    'pa-motion-sweep': "The foil button's light pass on hover: one sweep, never a loop.",
    'leading-tight': 'Tight leading for display headings.',
    'leading-snug': 'Snug leading for short multi-line labels.',
    'leading-normal': 'Body leading for reads.',
    'leading-relaxed': 'Relaxed leading for long prose and captions.',
    'font-weight-normal': 'Body and display weight.',
    'font-weight-medium': 'Kicker and emphasized label weight.',
    'font-weight-semibold': 'Active chip and segment weight.',
    'font-weight-bold': 'Strong emphasis in prose.',
    'shimmer-angle': 'Angle of the shimmer utility\'s light band.',
    'scroll-fade-mask': 'Internal to the scroll-fade utility; set per element.',
    'shimmer-image': 'Internal to the shimmer utility; unset means its own default.',
    'animate-spin': 'Spinner loop for loading indicators.',
    'animate-pulse': 'Pulse loop for skeleton placeholders.',
    'aspect-video': 'The 16:9 video frame ratio.',
    'lightningcss-dark': 'Compiler switch for dark color-scheme values; not a design token.',
    'foil': 'The foil: electric burnt chrome, the only metallic. Clips into the ATLAS wordmark, filed-specimen names and a few headings, and rims the chrome button.',
    'gold': 'Retired: the old gold 1/1 gradient. The site no longer declares or reads it; the 1/1 is `ember`, which lives in components/bundle.css.',
    'tracking-tight': 'Tight tracking for large display type.',
    'tracking-wide': 'Slightly open tracking for small caps.',
    'tracking-label': 'The micro-label tracking (0.18em) every mono label uses.',
}
