# Usage notes for every token, written from the site's stylesheet (src/index.css at
# main@4098cbd) and measured in a browser: the value at the top level, and what
# changes inside `.field-cream`, the one cream scope.
CREAM = 'inside `.field-cream` it is'

COLOR = {
    'color-black': 'Pure black. Tailwind base color; the brand reaches for `color-void` instead.',
    'color-white': 'Pure white. Tailwind base color.',
    'color-paper': f'The heritage page paper. The site remaps it to the void (#070509) at the top level so legacy `bg-paper` surfaces read dark; {CREAM} the cream ground #f4eee0.',
    'color-paper-2': f'Deeper heritage paper for alternating sections. Void-panel #0e0b15 at the top level; {CREAM} #eae2d2.',
    'color-stage': 'The warm stage behind hero and colophon (`.on-stage`); the same near-black as the void.',
    'color-press': 'Raised warm charcoal: cards on the table. The ground of the `Card` component and `.rfx-panel`, edged in bone at 10%; `color-bone` reads 14.7:1 on it.',
    'color-ink': 'Primary ink, and it follows the ground: bone #f6f1e6 on the open page and inside panels and plates; inside `.field-cream` it is #14161b (15.6:1 on cream).',
    'color-ink-2': 'Secondary ink, and it follows the ground: cool #c2c7d6 on the open page (12.0:1), warm #c9c2b0 inside panels and plates (9.3:1 on `color-press`); inside `.field-cream` it is slate #3f4654 (8.2:1 on cream).',
    'color-ink-3': 'Muted ink, and it follows the ground: #7c8294 on the open page (5.3:1), #969080 inside panels and plates (5.2:1 on `color-press`); inside `.field-cream` it is #5c6473 (5.2:1 on cream). The cream hairline is mixed from it.',
    'color-seam': 'The seam red. #ff2d44 on the void (5.5:1), the same as `color-seam-bright`; inside `.field-cream` it is #c8102e (5.1:1 on cream), and panels and plates pin it back to #ff2d44. The site-wide focus outline draws it. Never set small text in #c8102e on the void (3.45:1).',
    'color-seam-deep': 'Pressed seam red: #d02539 on the void; inside `.field-cream` it is #c8102e darkened toward #2a0a10. Only `cta-bg-hover` names it, and nothing on the site paints either.',
    'color-powder': 'Columbia powder blue, the same on every ground: a secondary accent in text and borders (11.0:1 on the void).',
    'color-navy': f'Heritage navy for prestige and structure. Remapped to warm light #d8d1c0 on the void; {CREAM} #0c2340.',
    'color-navy-2': 'Lifted navy. #efe9da on the void; inside `.field-cream` it is #15406e. Nothing on the site paints it.',
    'color-navy-line': f'Faint navy line for plate borders. 16% warm light on the void; {CREAM} navy at 22%.',
    'color-cta-text': 'White for text on the red CTA field (`cta-text`): 3.7:1 on the #ff2d44 that `cta-bg` holds, under the 4.5:1 a label needs. Nothing on the site paints the pair.',
    'color-leather': 'Saddle leather: the kicker ink on the cream field (6.4:1 on cream) and the brand-mark diamond edge.',
    'color-ok': 'Official-data green by name. #34e27e on the void (same as `color-ok-bright`); inside `.field-cream` it is #2e7d55. Nothing on the site paints it; the official dot uses `color-ok-bright`.',
    'color-amber': f'Reputable-analysis amber. #ffc23c on the void; {CREAM} #b07a1e.',
    'color-sand': 'Secondhand sand by name. #cdba8e on the void; inside `.field-cream` it is #8a7a5e. Nothing on the site paints it; the secondhand dot uses `color-sand-bright`.',
    'color-machined': f'The machined hairline tone the `.hairline` fade is drawn in. Warm light at 20% on the void; {CREAM} slate at 38%.',
    'color-dim': 'Legacy dim text, an alias of `color-ink-2`. Declared in source but unused by any shipped rule.',
    'color-void': 'The cool near-black field: every page sits on it. No page sets its own light background.',
    'color-bone': 'Primary text on the void (18.0:1) and on `color-press` panels (14.7:1). It holds its value on every ground, so it reads only on dark ones.',
    'color-bone-2': 'Warm secondary text and captions on the void (11.4:1) and on panels (9.3:1). It holds its value on every ground; inside panels and plates `color-ink-2` turns to the same hex.',
    'color-ok-bright': 'Official-data dot (`ConfidenceDot`), tuned for the dark field; 11.9:1 on the void. Status, never decoration; always beside its tier label.',
    'color-amber-bright': 'Reputable-analysis dot (`ConfidenceDot`) on the dark field; 12.6:1 on the void.',
    'color-sand-bright': 'Secondhand and community dot (`ConfidenceDot`) on the dark field; 10.6:1 on the void.',
    'color-cyan': 'The interaction voice on the void: inline links, focus (`ring`), active chips and segments (`ctl-accent`), the kicker, and the pitcher-own-words dot. 12.9:1 on the void.',
    'color-cyan-deep': 'Deeper cyan. No stylesheet rule reads it.',
    'color-seam-bright': 'The void-tuned seam red, the same on every ground: the unverified dot (`ConfidenceDot`) and the red edge on marked plates (`.rfx-plate.is-edge`), such as the legends in the lost-pitches hall. 5.5:1 on the void.',
    'color-violet': 'Steel-blue palette color. No stylesheet rule reads it; pitch families take their own accents (see the brand book).',
    'color-teal-glow': 'Teal text accent (`text-teal-glow`) and the coach-observed dot (`ConfidenceDot`); the same teal is a band in the foil. 5.8:1 on the void.',
    'bevel-hi': 'Inset top highlight on the stage portrait frame (`.pa-stage-portrait`).',
    'bevel-lo': 'Paired bevel shade. No stylesheet rule reads it.',
    'color-columbia': 'Columbia blue, a heritage accent. No stylesheet rule reads it.',
    'cb-paper': 'Card-back stock. Declared on `.rfx-cardback`, the cream reverse of a specimen card.',
    'cb-paper-2': 'Deeper card-back stock, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'cb-ink': 'Primary ink on the card back (`.rfx-cardback`).',
    'cb-ink-2': 'Secondary ink on the card back, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'cb-ink-3': 'Muted ink on the card back, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'cb-line': 'Rules on the card back.',
    'cb-navy': 'Navy accent on the card back.',
    'cb-forest': 'Forest accent on the card back, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'cb-burgundy': 'Burgundy accent on the card back, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'cb-gold-ink': 'Gold-ink accent on the card back, declared on `.rfx-cardback`. Nothing on the site reads it.',
    'plate-edge': 'Edge of a specimen plate. Declared on `.rfx-plate`, where it follows the pitch family accent (`--gc`).',
    'spec-accent': 'Specimen accent inside a specimen scope; follows `color-cyan`.',
    'color-paper-3': 'Heritage cream sand edge. #16121f on the void; inside `.field-cream` it is #d8cfb8. Nothing on the site paints it.',
    'color-cream': 'Alias of the cream surface: the void at the top level; inside `.field-cream` it is #f4eee0. Nothing on the site paints it.',
    'color-panel': 'Heritage panel. #0e0b15 on the void; inside `.field-cream` it is #eae2d2. Nothing on the site paints it.',
    'kicker': f'Section eyebrow ink (`Kicker`, `.rfx-skick`). Cyan on the void; {CREAM} leather #7a4a2e.',
    'ctl-bg': f'Form control ground (`.rfx-input`, `.rfx-select`). #0b0805 on the void; {CREAM} #fffdf6.',
    'ctl-text': f'Form control text. Bone on the void; {CREAM} ink #14161b.',
    'ctl-placeholder': 'Placeholder text in controls. #7c8294 reads 5.3:1 on the void but 4.3:1 on `color-press`; inside `.field-cream` it is #5c6473.',
    'ctl-border': f'Control border: cyan at 40%, resolved from `color-mix(in srgb, var(--color-cyan) 40%, transparent)`; {CREAM} leather at 45%.',
    'ctl-accent': f'Active chip and segment fill (`Tag active`, `SegmentedToggle`). Cyan on the void; {CREAM} seam red #c8102e.',
    'ctl-on-accent': f'Text on an active chip or segment. #06121b on cyan reads 12:1; {CREAM} white on red.',
    'background': f'shadcn page ground for the generic primitives. The void; {CREAM} #f4eee0.',
    'foreground': f'shadcn text on `background`. Bone; {CREAM} ink.',
    'card': f'shadcn card ground. #0e0b15; {CREAM} #eae2d2.',
    'card-foreground': 'shadcn text on `card`.',
    'popover': f'Ground of open popovers: the Select list and menus. #0e0b15; {CREAM} #fffdf6.',
    'popover-foreground': 'Text on `popover`.',
    'primary': "The primary-action voice: electric burnt orange, the fill of every generic primary action (the report dialog's submit, for one). Cyan stays the interaction voice. Inside `.field-cream` it is #a83607 for contrast on cream.",
    'primary-foreground': f'Ink on a `primary` fill: #1a0a04 on burnt orange reads 6.7:1; {CREAM} white.',
    'secondary': f'shadcn secondary ground. #16121f; {CREAM} #eae2d2.',
    'secondary-foreground': 'Text on `secondary`.',
    'muted': f'shadcn muted ground. #16121f; {CREAM} #eae2d2.',
    'muted-foreground': 'Muted text on the void (12:1). Inside `.field-cream` it is #3f4654.',
    'accent': f'shadcn hover ground for list items. #0e0b15; {CREAM} #eae2d2.',
    'accent-foreground': 'Text on `accent`.',
    'destructive': f'Destructive actions, the seam red. #ff2d44; {CREAM} #c8102e.',
    'border': f'shadcn border: bone at 12%; {CREAM} ink at 14%.',
    'input': f'shadcn input border: bone at 14%; {CREAM} ink at 18%.',
    'ring': 'Focus ring of the generic primitives: cyan. The site also draws a 2px `color-seam` outline on every focus-visible control. Inside `.field-cream` it is #1f6e78.',
    'chart-1': 'shadcn chart default, still the old cyan. Declared but read by nothing the site ships.',
    'chart-2': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-3': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-4': 'shadcn chart default. Declared but read by nothing the site ships.',
    'chart-5': 'shadcn chart default. Declared but read by nothing the site ships.',
    'sidebar': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-primary': 'shadcn sidebar default, still the old cyan. Declared but read by nothing the site ships.',
    'sidebar-primary-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-accent': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-accent-foreground': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-border': 'shadcn sidebar default. Declared but read by nothing the site ships.',
    'sidebar-ring': 'shadcn sidebar default, still the old cyan. Declared but read by nothing the site ships.',
    'color-press-2': 'Deeper press (#16130f). Only `surface-card-2` names it, and nothing on the site paints either.',
    'color-bone-3': 'Tertiary bone. Nothing on the site paints it by this name (its `text-bone-3` class has no rule behind it), but the same hex is what `color-ink-3` turns to inside panels and plates (5.2:1 on `color-press`).',
    'surface-page': 'Semantic alias of `color-void`, the page ground. Nothing on the site reads it; pages paint `color-void`.',
    'surface-stage': 'Semantic alias of `color-stage`, the ground for heroes and the colophon. Nothing on the site reads it.',
    'surface-card': 'Semantic alias of `color-press`, the raised card ground; inside `.field-cream` it is #eae2d2. Nothing on the site reads it; `.rfx-panel` paints `color-press`.',
    'surface-card-2': 'Semantic alias of `color-press-2`. Nothing on the site reads either.',
    'surface-cream': 'The cream ground (#f4eee0) by name. Nothing on the site reads it; inside `.field-cream`, `color-paper` holds the same value.',
    'surface-cream-2': 'The deeper cream (#eae2d2) by name. Nothing on the site reads it; inside `.field-cream`, `color-paper-2` holds the same value.',
    'text-fg': 'Semantic primary text: bone on the void; inside `.field-cream` it is ink. Nothing on the site reads it; text paints `color-ink` or `color-bone`.',
    'text-fg-2': 'Semantic secondary text: `color-bone-2` on the void; inside `.field-cream` it is #3f4654. Nothing on the site reads it.',
    'text-fg-muted': 'Semantic muted text: `color-bone-3` on the void; inside `.field-cream` it is #5c6473. Nothing on the site reads it; muted text paints `color-ink-3`.',
    'cta-bg': 'Red CTA field by name. It is set from `color-seam` once, at the top of the page, so it stays #ff2d44 inside `.field-cream` too. Nothing on the site reads it; the foil button draws its own rim.',
    'cta-bg-hover': 'Pressed red CTA field by name (#d02539), set from `color-seam-deep` at the top of the page and unchanged inside `.field-cream`. Nothing on the site reads it.',
    'cta-text': 'Text on the red CTA field by name: white, 3.7:1 on `cta-bg`, under the 4.5:1 a label needs. Nothing on the site reads it.',
    'focus-ring': "The focus color by name, set from `color-seam` at the top of the page, so it stays #ff2d44 inside `.field-cream`. Nothing reads it: the site's focus outline is 2px of `color-seam` itself, offset 3px, which does turn #c8102e on cream.",
    'confidence-official': 'Official-data dot by name; inside `.field-cream` it is #2e7d55. Nothing on the site reads it; `ConfidenceDot` paints `color-ok-bright`.',
    'confidence-reputable': 'Reputable-analysis dot by name; inside `.field-cream` it is #b07a1e. Nothing on the site reads it; `ConfidenceDot` paints `color-amber-bright`.',
    'confidence-secondhand': 'Secondhand, attributed dot by name; inside `.field-cream` it is #8a7a5e. Nothing on the site reads it; `ConfidenceDot` paints `color-sand-bright`.',
    'confidence-unverified': 'Unverified dot by name, gray #969080 on every ground. Nothing on the site reads it, and it disagrees with the site: `ConfidenceDot` paints an unverified claim red (`color-seam-bright`, #ff2d44).',
    'border-card': 'Card edge by name: bone at 10% on the void; inside `.field-cream` it is navy at 14%. Nothing on the site reads it; `.rfx-panel` sets the same bone 10% edge directly.',
    'hairline-void': 'Hairline on the void by name: bone at 12%. Nothing on the site reads it; the `.hairline` fade draws `color-machined`, and `Hairline stage` a fixed warm-bone fade (#f2ecdd at 22%).',
    'hairline-cream': 'Hairline on cream by name: navy at 18%. Nothing on the site reads it; inside `.field-cream` the `.hairline` fade draws `color-machined` (slate at 38%).',
}

OTHER_FAMILIES = {
    'tweet-body-margin': 'Internal to the embedded-tweet widget (`.react-tweet-theme`); not a brand spacing step.',
    'tweet-actions-icon-size': 'Internal to the embedded-tweet widget; not a brand spacing step.',
    'scroll-fade-t': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-b': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-s': 'Internal to the scroll-fade edge mask utility; set per element.',
    'scroll-fade-e': 'Internal to the scroll-fade edge mask utility; set per element.',
    'spacing': 'The 4px step every padding, gap and margin multiplies (Tailwind `p-4` = 4 × this).',
    'container-xs': 'Narrow column width (20rem).',
    'container-sm': 'Small column width (24rem).',
    'container-lg': 'Card and form column width (32rem).',
    'container-2xl': 'Reading column width (42rem).',
    'container-3xl': 'Wide reading column (48rem).',
    'container-4xl': 'Section content width (56rem).',
    'container-5xl': 'Wide section width (64rem).',
    'container-6xl': 'Page content width (72rem).',
    'blur-xs': 'Smallest backdrop and glow blur.',
    'blur-sm': 'Small blur for soft glows.',
    'blur-md': 'Medium blur for overlays.',
    'blur-2xl': 'Large blur. No shipped rule reads it any more.',
    'rfxu': 'The refractor card unit: 1% of the card\'s own width (`1cqw` on `.rfx-card`), so a card\'s type and chrome scale with the card. 3.6px is its value at the 360px default.',
    'mx': 'Pointer x on a refractor card (drives the foil rake); set per card, 50% at rest.',
    'my': 'Pointer y on a refractor card; set per card, 32% at rest.',
    'radius-sm': 'Small corner: chips\' inner parts, inputs, the focus outline. Resolves from `--radius` × 0.6.',
    'radius-md': 'Medium corner for buttons and panels. `--radius` × 0.8.',
    'radius-lg': 'Large corner for cards and dialogs; equal to `--radius`.',
    'radius': 'The base corner every other radius derives from.',
    'radius-pill': 'Full pill, for filter chips and status pills only.',
    'ease-in': 'Tailwind ease-in. No shipped rule reads it; use `pa-ease-settle`.',
    'ease-out': 'Tailwind ease-out, for generic transitions in the primitives.',
    'ease-in-out': 'Tailwind ease-in-out, the default transition curve in the primitives.',
    'default-transition-duration': 'Tailwind\'s default transition length (150ms) for the generic primitives.',
    'default-transition-timing-function': 'Tailwind\'s default transition curve for the generic primitives.',
    'pa-ease-settle': 'The one house easing: a quick start that settles into stillness. Use it for every brand motion; a few older transitions (the card tilt, the specimen view transition) still carry their own curves.',
    'pa-motion-tiny': 'Press, focus and hover.',
    'pa-motion-short': 'A state change or chip settle.',
    'pa-motion-medium': 'A positional move.',
    'pa-motion-slow': 'A one-shot scroll reveal.',
    'pa-motion-sweep': "The foil button's light pass on hover: one sweep, never a loop.",
    'leading-tight': 'Tight leading for display headings.',
    'leading-snug': 'Snug leading for short multi-line labels.',
    'leading-normal': 'Body leading for reads.',
    'leading-relaxed': 'Relaxed leading for long prose and captions.',
    'font-weight-normal': 'Body and display weight.',
    'font-weight-medium': 'Kicker and emphasized label weight.',
    'font-weight-semibold': 'Active chip and segment weight.',
    'font-weight-bold': 'Strong emphasis in prose.',
    'shimmer-angle': 'Angle of the shimmer utility\'s light band.',
    'scroll-fade-mask': 'Internal to the scroll-fade utility; set per element.',
    'shimmer-image': 'Internal to the shimmer utility; unset means its own default.',
    'animate-spin': 'Spinner loop for loading indicators.',
    'animate-pulse': 'Pulse loop for skeleton placeholders.',
    'aspect-video': 'The 16:9 video frame ratio.',
    'lightningcss-dark': 'Compiler switch for dark color-scheme values; not a design token.',
    'foil': 'The foil: electric burnt chrome, the only metallic. Clips into the ATLAS wordmark, filed-specimen names and a few headings, and rims the chrome button.',
    'gold': 'Retired: the old gold 1/1 gradient. The site no longer declares or reads it; the 1/1 is `ember`, which lives in components/bundle.css.',
    'tracking-tight': 'Tight tracking for large display type.',
    'tracking-wide': 'Slightly open tracking for small caps.',
    'tracking-label': 'The micro-label tracking (0.18em) every mono label uses.',
}
