import type { PitchAtlasEntry, SeamAnchoredPoint } from '../types'
import { claim } from '../sources'
import { sharedSeam } from './_shared-seam'

/*
  The 12-6 curveball. The four-seam's mirror: topspin instead of backspin, so the
  Magnus force points down and adds to gravity. Large induced drop, little
  horizontal break. Grip prose paraphrased from Driveline, never copied. No player
  image, no likeness.

  Authored against an independent verification pass. One correction it forced:
  Kershaw's 2024 curveball horizontal break is ~6.6 in glove-side (the 4.4 figure
  is a 2025 value), applied everywhere it appears.
*/

const fingerPlacement: SeamAnchoredPoint[] = [
  { seamT: 0.3, lift: 0.02, label: 'Middle', finger: 'middle', note: 'Leverages a seam, commonly the inside edge of the horseshoe.' },
  { seamT: 0.255, lift: 0.02, label: 'Index', finger: 'index', note: 'Rests on the leather beside the middle finger.' },
  { seamT: 0.8, lift: 0.0, label: 'Thumb', finger: 'thumb', note: 'Underneath on a seam; the ball is tucked back toward the palm to load spin.' },
]

export const twelveSix: PitchAtlasEntry = {
  canonical: {
    id: 'twelve-six-curveball',
    name: '12-6 curveball',
    family: 'breaking',
    grip: claim(
      'The hand gets on top of the ball so the fingers impart pure topspin. The middle finger leverages a seam, the index rests on the leather beside it, the thumb sits underneath on a seam, and the ball is tucked back toward the palm to load spin.',
      'driveline-curveball',
      'reputable-analysis',
      { note: 'Paraphrased from Driveline, not quoted. Spike and knuckle variants are a common feel-based alternative.' },
    ),
    gripDetails: [
      claim(
        'Driveline\'s standard curve grip leverages the middle finger on the seam with the index on the leather and the thumb on a seam underneath. Topspin comes from getting the fingers in front of the ball and pulling down, the cue being to yank it down with the middle finger.',
        'driveline-curveball',
        'reputable-analysis',
        { note: 'Paraphrased. Spike "CB 3-4" variants live on the same page.' },
      ),
      claim(
        'The name is the clock face: the break runs in a straight line from 12 to 6. A higher arm slot makes it more vertical, a true 12-6; a lower slot tilts it toward a 1-7 slurve with more sideways movement.',
        'baseballmonkey-curveball',
        'reputable-analysis',
        { note: 'Paraphrased coaching reference for the clock-face naming and the arm-slot relationship.' },
      ),
    ],
    fingerPlacement,
    mechanics: claim(
      'Topspin is generated by getting on top of the ball and driving the fingers over the front of it, pulling down so it rotates forward rather than with a slider\'s lateral tilt. Per Driveline, a higher release point leads to a more top-down movement profile, the classic 12-6, while lower slots add horizontal movement and turn it into a slurve.',
      'driveline-curveball',
      'reputable-analysis',
      { note: 'Paraphrased from Driveline. The fastball-mirror framing is grounded in the MLB.com IVB glossary.' },
    ),
    physics: {
      spinAxis: claim(
        'Near-pure topspin: the axis lies roughly horizontal and points the Magnus force straight down. Kershaw\'s curve, the cleanest modern 12-6, sits near a 5:30 clock with 85% active spin. More glove-side tilt makes a diagonal power curve instead.',
        'savant-kershaw',
        'official-data',
        { note: 'Kershaw 2024: observed 5:30, spin-based 5:15, 85% active spin, from Savant.' },
      ),
      spinRateRpm: claim(
        'High. The MLB-average curveball spun about 2,523 rpm in 2019; elite 12-6 curves sit well above. Kershaw runs about 2,242, and high-spin power curves like Morton\'s reach 3,000 and up.',
        'mlb-glossary-spin-rate',
        'reputable-analysis',
        { approximate: true, note: 'Player and season dependent. Exact rpm from Savant arsenal data.' },
      ),
      activeSpinPct: claim(
        '85% on a clean 12-6 (Kershaw, 2024): almost all of the spin is working topspin that drives the drop.',
        'savant-kershaw',
        'official-data',
        { note: 'From the Savant spin-direction table.' },
      ),
      primaryBreak: {
        label: 'Induced vertical break',
        accent: true,
        claim: claim(
          'Large induced drop. MLB curveballs averaged about -10 inches in 2024, the most induced drop of any pitch; the biggest 12-6 curves reach -15 and beyond. Kershaw\'s is -15.3.',
          'mlb-ivb',
          'official-data',
          { note: 'Negative induced vertical break means it drops more than a spinless pitch. The glossary names Fried, Yamamoto, and Kershaw as large-drop curveball throwers.' },
        ),
      },
      secondaryBreak: {
        label: 'Horizontal break',
        claim: claim(
          'Little to none is the mark of a TRUE 12-6. Kershaw breaks only about 6.6 inches glove-side, close to straight down; curves running 10 to 16 inches glove-side read as 1-7 power curves instead.',
          'savant-kershaw',
          'official-data',
          { approximate: true, note: 'Kershaw 2024 horizontal break ~6.6 in glove-side per Savant. Minimal horizontal is the hallmark of a 12-6.' },
        ),
      },
      teaching: claim(
        'The curve is the four-seam fastball\'s mirror. The fastball spins backspin, so its Magnus force points up and it rides; the 12-6 spins topspin, so its Magnus force points down and it drops. Same physics, flipped axis, which is why a four-seam carries about +16 inches of induced break and a curveball drops about -10.',
        'mlb-ivb',
        'official-data',
        { note: '2024 MLB four-seamers averaged +16 in induced vertical break (most rise), curveballs -10 in (most drop), the mirror relationship.' },
      ),
    },
    rights: 'original',
  },

  motion: {
    // Topspin: the axis flips toward -x so magnusForceRender points down. Strength
    // ~0.85 matches Kershaw's active spin, so the down arrow runs nearly full length.
    spinAxis: { x: -0.85, y: -0.05, z: 0.52 },
    forceLabel: 'Magnus, down',
    ivbInches: -15.3,
    horizontalInches: 6.6,
    horizontalDir: 'glove-side',
    breakView: 'movement',
  },

  display: {
    slug: 'twelve-six',
    shortName: '12-6 curve',
    specimenNo: '03',
    heroSub: 'The fastball, mirrored.',
    heroIntro:
      'Topspin instead of backspin, so the Magnus force points down and joins gravity. It falls straight, 12 to 6, far more than a spinless ball would.',
    foundationCaption: 'Topspin points the Magnus force down. It drops far more than a spinless ball, with little sideways break.',
    mastersIntro:
      'A textbook 12-6 and the power curve beside it, to show where the straight-down line ends. The visual is our own seam schematic; every figure is season-stamped and sourced.',
  },

  masterVariants: [
    {
      tier: 'verified-attributed',
      pitcher: 'Clayton Kershaw',
      context: 'The textbook pure 12-6: almost all of its movement is straight-down induced drop with minimal horizontal run. MLB\'s own induced-break glossary names him as a large-drop curveball thrower.',
      verifiedPro: true,
      numbers: [
        { label: 'Induced vertical break', claim: claim('-15.3 in', 'savant-kershaw', 'official-data', { note: '2024. Negative is induced drop, far beyond the ~-10 in league average.' }) },
        { label: 'Horizontal break', claim: claim('6.6 in glove-side', 'savant-kershaw', 'official-data', { approximate: true, note: '2024. Minimal horizontal, the signature of a true 12-6.' }) },
        { label: 'Velocity', claim: claim('72.0 mph', 'savant-kershaw', 'official-data', { note: '2024, 81 thrown.' }) },
        { label: 'Spin direction', claim: claim('5:30, 85% active', 'savant-kershaw', 'official-data', { note: '2024 observed clock, near pure topspin.' }) },
        { label: 'Spin rate', claim: claim('~2,242 rpm', 'savant-kershaw', 'reputable-analysis', { approximate: true, note: 'Recent-season arsenal figure.' }) },
      ],
      rights: 'original',
    },
    {
      tier: 'verified-attributed',
      pitcher: 'Charlie Morton',
      context: 'The high-spin power-curve contrast. Elite spin, big total drop, but heavy glove-side tilt, an 8:00 axis, so it reads as a 1-7 power curve rather than a pure straight-down 12-6. It marks where the line ends.',
      verifiedPro: true,
      numbers: [
        { label: 'Induced vertical break', claim: claim('-8.9 in', 'savant-morton', 'official-data', { note: '2024. Less induced drop than Kershaw because more spin is tilted into horizontal break.' }) },
        { label: 'Horizontal break', claim: claim('13.6 in glove-side', 'savant-morton', 'official-data', { note: '2024. The large glove-side run that makes it a 1-7 power curve, not a 12-6.' }) },
        { label: 'Velocity', claim: claim('81.5 mph', 'savant-morton', 'official-data', { note: '2024, 1,183 thrown, his most-used pitch.' }) },
        { label: 'Spin rate', claim: claim('~3,085 rpm', 'savant-morton', 'reputable-analysis', { approximate: true, note: '2024 elite-tier; 2025 runs even higher.' }) },
      ],
      rights: 'original',
    },
  ],

  community: {
    enabled: false,
    safetyNote: 'Community variants will launch with age-aware visibility, source labels, and coach and parent safeguards.',
    provenanceNote:
      'When they open, every community variant will carry the same source and confidence labels as the records above. Nothing appears here unsourced, and no count is shown until it is real.',
    columns: ['Rank', 'Variant', 'Adoption', 'Source tier'],
  },

  seam: sharedSeam,
}
